default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: pedroneto
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: jambo_development
  
test:
  <<: *default
  database: jambo_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: jambo_production
  username: jambo-tech
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>