default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: pedroneto
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: code_a_city_development
  
test:
  <<: *default
  database: code_a_city_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: hackthon_code_a_city_production
  username: hackthon-code-a-city
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>